alex-shpak/hugo-book

- README.md
- exampleSite/config.yml
- layouts/partials/docs/git-footer.html
- layouts/posts/list.html
- layouts/posts/single.html
Please double check the **git-footer.html** as this is one I have not managed to abstract. I am quite new to this so...
Thanks, I hope it makes sense.
> Theme date formatting in config file

- .gitignore
- layouts/partials/docs/git-footer.html
- layouts/partials/docs/shared.html
Note that this requires this fix in Hugo 0.55.2:
https://github.com/gohugoio/hugo/issues/5865
> Adjust .File usage to get rid of WARNINGs

- assets/_markdown.scss
Refer to issues #48 
Here are the images detailing the issue: https://imgur.com/a/ysqlotN
> [Issues #48] Fix indentation and bg in highlight code block

- assets/_fonts.scss
I found it failed to load fonts/oxygen-* when not set base_url to root domain (For example, setting base_url to www.example.com/foo/).  After this fix it works for me.
> use relative path to load fonts/oxygen-*

- layouts/partials/docs/html-head.html
- search javascript
- SCSS processed stylesheet
> add sub resource integrity (SRI) to processed assets

- i18n/es.yaml
That was easy (no longer need to replace partials, yay!). I'm not sure about `bookSearchConfig`, though.
> Add es lang

- i18n/de.yaml
> German i18n file added

- i18n/sv.yaml
> Add Swedish i18n translation

- i18n/fr.yaml
This adds French localization to the theme.
> Add French localization

- README.md
Updated the list of features with Dark Mode.
> Added Dark Mode to features

- i18n/pt.yaml
> Adding portuguese i18n file

- README.md
Hi - This would have been really helpful if that was documented, many users aren't able to render the KaTex and aren't sure why/where to look
Also,  fixed spelling some spelling.
Cheers!
> Enabling KaTex Instructions

- i18n/cs.yaml
Czech `yaml` file added. Fixes #250.
> Added Czech translation

- i18n/de.yaml
Fixes wrong German translation (Issue #252).
> Corrected German translation

- README.md
- fix path of `menu/index.md` to match that given in the ExampleSite
- fix spelling
- fix grammar
- add missing articles
> Many minor fixes in README.md

- .github/workflows/main.yml
- Add `pull_request` event
- Use the `strategy.matrix` syntax
- Use peaceiris/actions-hugo: https://github.com/peaceiris/actions-hugo
Each job complete in 6s. (The duration is 1/3 than before.)
> Improve GitHub Actions workflow

- layouts/_default/baseof.html
https://gohugo.io/functions/hugo
> Add hugo.Generator

- layouts/_default/baseof.html
Added default (i.e. "ltr") value of "dir" attribute of "html" and "body" tags instead of empty.
> Added default dir="ltr"

- exampleSite/config.toml
- exampleSite/config.yaml
New users will have a Main branch to start with.
> change master to github's new default main branch

- assets/_main.scss
- layouts/partials/docs/menu-filetree.html
> collapsed menu right arrow, uncollapsed menu with down arrow

- README.md
> Alternate version of "Controllable Open Graph and Twitter Cards"

- assets/search.js
- i18n/fa.yaml
> add Farsi with support for search RTL texts 

- i18n/it.yaml
Hi, I just added an IT translation
> Added italian translation

- layouts/partials/docs/html-head.html
(to change scroll bar and inputs color automatically)
> add color-scheme to head-html

- README.md
Looks like the path `/book/` in the readme should be `/hugo-book/`.
> Updating book to hugo-book in README

- README.md
Hi 👋 . It's a very nice theme.
I got the following error while performing the [Creating site from scratch](https://themes.gohugo.io/themes/hugo-book/#creating-site-from-scratch) procedure.
```
$ hugo new site mydocs; cd mydocs
$ git init
$ git submodule add https://github.com/alex-shpak/hugo-book themes/hugo-book
$ cp -R themes/hugo-book/exampleSite/content .
cp: cannot stat 'themes/hugo-book/exampleSite/content': No such file or directory
```
I think it's related to the [move english content to content.en](https://github.com/alex-shpak/hugo-book/commit/9013a1f4570885416254aabbe7e389822d2fb215) change, and this PR intends to update the file path.
> Update step for creating site from scratch to use content.en path

- assets/_markdown.scss
> Format SCSS

- assets/_markdown.scss
Thank you for the awesome theme! Just a small improvement for the list tag.
| Before | After |
| ---- | ---- |
| <img width="500" alt="screenshot-before" src="https://user-images.githubusercontent.com/67619348/232178633-e2ace50e-9f10-4d5e-8b90-c41abcd04d65.png"> | <img width="500" alt="screenshot-after" src="https://user-images.githubusercontent.com/67619348/232178649-08ad8d0d-6dcf-47d6-96bb-14246062de93.png"> |
> Add "word-wrap" to list.

- layouts/partials/docs/footer.html
> fix: Fixed edit page support for multilang books

- i18n/oc.yaml
Hello!
This time I put the propper translation ah ah
I don't know what I did last time.
Regards
> i18n: Create oc.yaml

- i18n/pl.yaml
This adds Polish (PL/🇵🇱) translations within i18n directory.
> i18n: Add Polish translations

- layouts/shortcodes/hint.html
> fix: correct hint shortcodes rendering in lists

- assets/_main.scss
- layouts/_partials/docs/brand.html
- layouts/_partials/docs/footer.html
- layouts/_partials/docs/languages.html
- layouts/_partials/docs/prev-next-cache.html
- layouts/_partials/docs/prev-next.html
- static/svg/backward.svg
- static/svg/forward.svg
> Feature: Add next and previous page links

- exampleSite/hugo.toml
- exampleSite/hugo.yaml
> fix examplesite shortcodes link
