- layouts/partials/docs/html-head.html
- layouts/partials/docs/mobile-header.html
When base URL = `https://xxx/ggg`, `/normalize.min.css` would result in error 404.
> fix urls when baseURL is not at root

- layouts/partials/docs/html-head.html
Updated old `.RSSLink` call in partials/docs/html-head.html, which was throwing a warning, to use a `with` block and `.OutputFormats`.
> Updated to-be-deprecated .RSSLink call

- assets/book.scss
There's a display issue with pagination on blog post list pages:
I'm not super confident in my CSS knowledge so I don't know if this is the "correct" fix, but these are coming from the standard `list-style-type: disc`. Adding  `list-style-type: none` to `ul.pagination` in https://github.com/alex-shpak/hugo-book/blob/master/assets/book.scss#L79 fixed it for me.
> Fix bug: remove dots in blog post pagination ul

- assets/_markdown.scss
hi @alex-shpak 
I noticed that wide markdown tables don't scroll so I'm contributing this change. You can compare [before](https://deploy-preview-10--condescending-wing-a192db.netlify.com/) and [after](https://deploy-preview-12--condescending-wing-a192db.netlify.com/) by shrinking your browser down.
I'm no CSS expert, let me know if I should have down anything differently. thanks
> make markdown tables scroll

- README.md
- assets/book.scss
- exampleSite/config.toml
- exampleSite/config.yaml
- layouts/partials/docs/brand.html
Without a logo things look the same. With a logo the menu now has a bit of flair:
I've added documentation for how to use the logo in the README and the example configurations. I didn't feel comfortable picking a default logo for all sites, so did not add one.
> Optional brand logo in the menu controlled by .Site.Params.BookLogo

- layouts/partials/docs/footer.html
Seems to be a Windows related thing. `.File.Path` returns a path with backslashes this adds a replace to make those forward slashes. This appears to fix #115
> replacing any backslashes with forward slashes

- assets/_main.scss
- layouts/_default/baseof.html
- layouts/partials/docs/menu.html
- layouts/partials/docs/mobile-header.html
- layouts/partials/docs/toc.html
This allows the TOC to be visible from smaller devices in the same manner as the menu.
* Uses Page title as label
* Label entries so that tapping TOC will hide menu
> mobile toc menu

- README.md
- assets/_main.scss
- layouts/partials/docs/footer.html
This PR adds support for Disqus. If the standard Hugo `disqusShortname` configuration is provided, comments will be enabled for pages. This is a non-breaking change, comments are disabled by default.
Apologies if I've got something wrong here, am fairly new to Hugo!
Disqus can be disabled for any content by setting the following in the frontmatter:
```
disable_comments: true
```
See [effectiive-shell](https://effective-shell.com) for an example. Disqus is disabled on the main index page, and enabled for each chapter.
> feat: added support for Disqus

- assets/_main.scss
- assets/_print.scss
- layouts/_default/baseof.html
I haven't thoroughly experimented with this, but it seems to solve the problem I raised in #127. 
1. Removes `flex` class from `<main>`, adds the flex layout back in `_main.css`.
2. Alters the ordering of the child elements of main in the `baseof.html` template, so they run opposite of their current layout. (I imagine this point is most likely to cause problems, but in my brief testing I didn't notice any.)
3. `flex-direction` on `main` set to row-reverse, so it visually matches the current look. 
4. In `_print.css`, the `.book-menu` column is already hidden with `display: none`, so being in the different order doesn't matter. 
5. Changing `main`'s style in `_print.css` from `flex-direction: column-reverse;` to `display: block;` takes out the problematic `flex`, and with the new ordering …
> Removing flex from <main> for sake of print layout

- .github/workflows/main.yml
Fetch the latest tag (release) from GitHub API as variable, `LATEST_VERSION` (e.g. `v0.65.3`).
The `VERSION_NO_PREFIX` is a substring of `LATEST_VERSION` but with the first initial `v` removed (e.g. `0.65.3`).
Download the corresponding ".deb" package using the variables.
Tested locally.
Also, I just wanted to say thank you for making this theme, I use it on [utb.vilhelmprytz.se](https://utb.vilhelmprytz.se) which is a site for Swedish educational material :smile:
> GitHub Workflow: always use latest version of Hugo

- .github/workflows/main.yml
Added build job that checks with the minimum supported version of Hugo
**Note**: I have not tested this, I don't really know how to test the workflow locally. Is there any way you can try it out before merging with master (perhaps merging with another branch)?
(as discussed in #159)
> GitHub workflow: check with minimum supported version of Hugo

- exampleSite/config.toml
- exampleSite/config.yaml
- layouts/partials/docs/footer.html
Addresses #200
``` yaml
languages:                                                                      
en:                                                                           
languageName: English                                                       
contentDir: content/en                                                      
weight: 1                                                                   
ru:                                                                           
languageName: Russian                                                       
contentDir: content.ru                                                      
weight: 2
```
It looks like `.Site.Params.contentDir` will show the specific `contentDir` when the language is changed creating links such as
``` …
```
> Make 'Edit this page' content directory language independent

- layouts/partials/docs/header.html
The ToC icon was shown on smaller displays even if there was no ToC. It was confusing.
I decided to render the "label" tag but not the "img" tag so that the "justify-between" css-class still works and no changes to the stylesheet are necessary.
> Hide ToC icon in header if ToC not enabled

- README.md
I noticed this insignificant typo while configuring aspell for my site.
This corrects the path in the commented line to name `partials/docs/comments.html` with an `i` in partials.
> fix minor typo in README.md under Site Configuration

- layouts/shortcodes/button.html
Added " | markdownify" to the inner text of button.
> Let's enable markdown in the button title

- layouts/partials/docs/footer.html
When .Site.Params.contentDir is left as the default: "content", calling .Site.Params.contentDir returns nothing, or maybe an empty string. To fix this, we set a default value for .Site.Params.contentDir to "content" and the url is built correctly.
> Bug Fix: Empty .Site.Params.contentDir

- README.md
- exampleSite/content/docs/shortcodes/mermaid.md
Make it more obvious how to override the initialization configuration for Mermaid using `assets/mermaid.json`.
> Add documentation for mermaid init config override

- README.md
- exampleSite/config.toml
- exampleSite/config.yaml
- layouts/partials/docs/footer.html
- A new `BookCommitPath` paramter was added that allows the 'commit'
portion of the link to a page's last edited commit hash to be
specified.
- This is useful when github is not the default repository for a
project.
> Add custom commit path for last edited link

- layouts/_default/baseof.html
Fixed issue #336. HUGO does not use `{{ hugo.Generator }}` placeholder anymore.
> Fixed ineffective "disableHugoGeneratorInject" parameter

- README.md
- go.mod
This commit does the minimal work to make the Book theme a functional
hugo module by adding the go.mod file and including instructions in
the project README for use.
Resolves #375
> (GH-375) Enable use as a hugo module

- assets/_markdown.scss
When containing some extremely long lines, like attached below, hugo-book will let it overflow by default.
This PR is intended to change this behaviour to `break-words`, like attached below.
> prevent breaked-lines in <p>

- layouts/partials/docs/menu-filetree.html
This change allows hugo to build pages correcly when
`canonifyURLs = false` and `relativeURLs = true`.
Otherwise the links on the menu will be canonicalized regardless of
configuration.
This results in broken sites in a number of situations, such as sites
served behind a reverse-proxy that don't want to account for the prefix
they're served under.
> Make menu entries' link relative

- assets/clipboard.js
The previous solution for #281 forces copying entire code block content to clipboard while trying to select the part of it, which makes partial copying impossible.
This PR prevents copy-on-click inside code blocks if there is already an active selection.
New behavior:
- single-click – select and copy entire code block to clipboard
- click-and-drag – allow user to select part of the code
> Ignore code block clicks with active selection

- assets/_main.scss
As the tag `ul` style is setted blow at `_main.scss:64`:
```css
ul {
padding-inline-start: $padding-16;
}
```
So, to keep the pagination at the center of the page, the `ul.pagination` should not inherit that style.
> cover parent ul style

- layouts/partials/docs/title.html
Prior to this commit, the partial for determining a page title used the `Title` property of a page, if present, or humanized and titleized the file name if not.
It did not use the `LinkTitle` property at all (defined in the [front matter][01]). According to the [menu documentation][02]:
> The following order is used to determine an Identifier:
>
> `.Name > .LinkTitle > .Title`
>
> This means that `.Title` will be used unless `.LinkTitle is present, etc.
Similar, the documentation for [menu entry variables][03] states:
> The `name` key, if set for the menu entry, sets this value. If that key is not set, and if the menu entry is set in a page front-matter, this value defaults to the page's `.LinkTitle`.
Together, these imply that if `.LinkTitle` is specified, it should be preferred over …
> (MAINT) Respect LinkTitle in page metadata

- i18n/es.yaml
Added translation for 'Expand'.
Should be 'Expandir' instead.
> Update es.yaml to add missing translation

- layouts/partials/docs/html-head.html
https://github.com/alex-shpak/hugo-book/pull/468 was closed, but as suggested here https://github.com/alex-shpak/hugo-book/pull/468#issuecomment-1202471587, I think it works well.
- In the config: `BookTheme = 'auto'`
- iOS 16.3 Safari with Dark appearance
- No giscus
Before
After
> Update meta theme-color in html-head.html

- .github/workflows/main.yml
- exampleSite/config.toml
- exampleSite/config.yaml
Hi Alex, just two changes:
* the first editing the first line comment instruction on how to build in config.toml and config.yaml from `themesDir ...` to `..\..` which corrects the error stopping it from running (https://github.com/alex-shpak/hugo-book/issues/503).
* updating the actions/checkout@v2 to actions/checkout@v3, adding standard fetch of themes, and the standard use of peaceiris required(?) to deploy to GitHub Pages.
Let me know what you think. Thanks
> Themes dir correction and peaceiris deploy to GitHub Pages

- assets/manifest.json
- assets/sw-register.js
When baseURL is not the root directory：
Uncaught (in promise) DOMException: Failed to register a ServiceWorker for scope ('https://lizongying.github.io/') with script ('https://lizongying.github.io/go-crawler/docs/sw.js'): The path of the provided scope ('/') is not under the max scope allowed ('/go-crawler/docs/'). Adjust the scope, move the Service Worker script, or use the Service-Worker-Allowed HTTP header to allow the scope.
> fix server worker is blocked

- layouts/partials/docs/html-head.html
This PR fixes the issue raised in #574.
> Fix: make use of .Site.Params.BookFavicon

- exampleSite/config.toml
- exampleSite/config.yaml
The current link (https://themes.gohugo.io/hugo-book/) redirects to https://themes.gohugo.io/themes/hugo-book/.
I thought I'd update it before the current one is deprecated.
> Update link to hugo themes

- README.md
So that it is correctly displayed at https://themes.gohugo.io/themes/hugo-book/.
See https://github.com/gohugoio/hugoThemesSiteBuilder#use-absolute-paths-for-images.
> Make image path absolute

- layouts/partials/docs/footer.html
Closes #592
It seems quite clear to me:
- menu, toc and translate benefit from alt text
- calendar and edit don't
> Use null alt text for calendar.svg and edit.svg

- assets/_markdown.scss
Thanks for this theme; it's awesome. I'm using it with the Arabic language, and it supports RTL very well. However, code and highlights should always be LTR regardless of the blog site's language. Here is a proposed change that will ensure the code and highlights always appear LTR. Thank you.
> Add direction ltr to pre > code and highlight

- layouts/partials/docs/menu.html
The warning
```
INFO  deprecated: .Site.IsMultiLingual was deprecated in Hugo v0.124.0
and will be removed in a future release. Use hugo.IsMultilingual
instead.``
shows up
Follow the deprecation warning
> replace .Site.IsMultiLingual with hugo.IsMultilingual

- .github/workflows/main.yml
- layouts/partials/docs/brand.html
- layouts/partials/docs/html-head.html
- theme.toml
When running example site with latest hugo version 0.134.2, deprecation warnings are shown.
This PR fixes these issues.
This PR closes #622.
> Fix deprecation warnings

- exampleSite/content.en/docs/shortcodes/tabs.md
- layouts/shortcodes/tab.html
- layouts/shortcodes/tabs.html
Use [.Ordinal](https://gohugo.io/methods/shortcode/ordinal/) instead of user-provided string argument to generate a unique ID for `tabs`. It makes the tabs easier to use, no need to come up with a unique name for each tabs group anymore.
The change is backward-compatible: user-provided ID will be simply ignored.
> Auto-generate ID for tabs

- layouts/shortcodes/mermaid.html
"mindmap" style is not rendered correctly with "--minify"  because spaces are removed from final HTML
> Fix for spaces being removed during "minify" build for "mermaid" snippet

- layouts/partials/docs/html-head.html
The hugo default function returns second argument if set and first if second is not set.
Before this PR, second parameter is site.languagecode which is current language code, not language of translation.
After this PR, correctly use language code of translation
> fix: hreflang for link rel=alternate uses site language code

- .gitignore
- README.md
- layouts/partials/docs/brand.html
- layouts/partials/docs/html-head.html
- layouts/partials/docs/menu.html
- resources.ToCSS was deprecated in Hugo v0.128.0 and will be removed in a future release. Use css.Sass instead.
- deprecated: .Sites.First was deprecated in Hugo v0.127.0 and will be removed in a future release.
- ERROR deprecated: .Site.IsMultiLingual was deprecated in Hugo v0.124.0 and will be removed in Hugo 0.137.0.
> Three hugo deprecations

- exampleSite/content.en/docs/shortcodes/tabs.md
The syntax of `{{% code %}}` only expects Markdown inside. That's why it triggers unsafe warning, if used as a shortcode template.
Instead the only the top table shortcode should be used as `{{< tabs >}}` to include the HTML, while the user may use only `{{% tab "Name" %}}` inside and be happily restricted to Markdown.
https://gohugo.io/methods/page/rendershortcodes/#shortcode-notation
https://github.com/InfosecForActivistsTeam/infosec-activists/pull/45
---
I have not added any notes to README.md. Yes, I have tested with unsafe=false and the tabs worked while other pages generated warnings.
> Docs: Change tabs shortcode example to permit unsafe=false

- layouts/posts/single.html
fix: change article title from h2 to h1 in single.html
Corrected the semantic structure of article pages by using h1 for the main title
instead of h2. This ensures proper HTML semantics with only one h1 per page,
improving both accessibility and SEO performance.
> fix: change article title from h2 to h1 in single.html

- assets/_main.scss
Add `scrollbar-gutter: stable` to the root html element.
Per [MDN](https://developer.mozilla.org/en-US/docs/Web/CSS/scrollbar-gutter):
> The scrollbar-gutter [CSS](https://developer.mozilla.org/en-US/docs/Web/CSS) property allows authors to reserve space for the scrollbar, preventing unwanted layout changes as the content grows while also avoiding unnecessary visuals when scrolling isn't needed.
This means that when navigating between pages long enough to show a scrollbar and pages short enough to be displayed without one, content like sidebars, centered elements, etc all stay in exactly the same place.
> Add scrollbar-gutter: stable

- layouts/_default/_markup/render-link.html
Linking to a heading on the same page should not be affected by the `BookPortableLinks` setting.
`.Page.GetPage` would return the homepage for a empty path, breaking links to headings on any other page than the homepage. This PR fixes that by skipping URLs that only contain a fragment.
> fix: links to fragment on same page should not be made portable

- README.md
This parameter is already used in `layouts/_partials/docs/html-head-favicon.html`, I just added documentation so it's easy to find.
> Add BookFavicon param to readme

- layouts/_partials/docs/toc-show.html
When `.Site.Params.BookToC` is not set, it defaults to `true`.  Before this change the whole expression in toc-show.html always returned `false`, when `.Site.Params.BookToC` was not set.
Related to https://github.com/alex-shpak/hugo-book/issues/750#issuecomment-3157464974.
> toc-show.html: enforce default value true for .Site.Params.BookToc
